config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  get '/' => 'home#index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: %i[new create], path_names: { new: '' }
  resources :users, only: %i[index show]
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  has_many :comments

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @articles = Article.order('created_at DESC').all
  end

  def show
    @article = Article.find(params[:id])
    # @users = User.all
    # @users = User.where(username: @article.author).first
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render action: 'new' # new_contacts_path
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render action: 'edit' # new_contacts_path
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :author)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render 'new' # new_contacts_path
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <% if @article && @article.errors.any? %>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :title%><br>
    <%= f.text_field :title, style: 'width:100%;' %>
  </p>

  <p>
    <%= f.label :text%><br>
    <%= f.text_area :text, style: 'width:100%; height: 150px' %>
  </p>

  <p>
    <%= f.submit class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <hr>
  <h2>
    <%= article.title %>
  </h2>
  <p>
    <%= truncate(article.text, length: 130) %><br>
  </p>
  <p>
    <%= link_to "Show(#{article.comments.size})", article_path(article) %>
    <% if article.author == current_user.username %>
     | <%= link_to 'Edit', edit_article_path(article) %> |
      <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Вы уверены?' } %>
    <% end %>
  </p>
  <hr>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.hidden_field :author, { :value => current_user.username } %>
  </p>

  <p>
    <%= f.label :title%><br>
    <%= f.text_field :title, style: 'width:100%;' %>
  </p>

  <p>
    <%= f.label :text%><br>
    <%= f.text_area :text, style: 'width:100%; height: 150px' %>
  </p>

  <p>
    <%= f.submit class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p>
  <%= @article.text %>
</p>
<hr>
<% @article.comments.each do |comment| %>
  <hr>
    <div class="bs-example">
      <%= comment.body %><br>
      <p align="right" style="font-size: small">
        <i>
          Created by: <%= comment.author %> at: <%= comment.created_at.to_date %>
        </i>
      </p>
    </div>
  <hr>
<% end %>
  <%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.hidden_field :author, { :value => current_user.username } %>
  </p>

  <p>
    <%= f.label :body%><br>
    <%= f.text_area :body, style: 'width:100%; height: 150px' %>
  </p>

  <p>
    <%= f.submit class: 'btn btn-primary' %>
  </p>
  <% end %>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact && @contact.errors.any? %>
    <p>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
  <p>
    <%= f.label :email%><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :message%><br>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit 'Отправить сообщение' %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<header class="clearfix col-md-12" id="nav-header">
  <div class="navbar-header">
    <div class="navbar-collapse">
      <ul>
        <li><a style="font-weight: bold; font-size: x-large" href="/">Blog</a></li>
        <li><a href="/articles">Статьи</a></li>
        <li><a href="/articles/new">Новая статья</a></li>
        <li><a href="/users">Пользователи</a></li>
        <li><a href="/contacts">Контакты</a></li>
      </ul>
      <ul class="pull-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Edit my profile', edit_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!--    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">-->
<!--    <link data-require="bootstrap@*" data-semver="4.1.3" rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />-->
<!--    <script data-require="bootstrap@*" data-semver="4.1.3" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>-->

<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->


    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <%= render 'layouts/header' %>
            </div>
            <div class="content">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <% else %>
        <div class="container devise-container">
          <%= link_to 'Sign In', new_user_session_path %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>О нас</h1>

app/views/pages/terms.html.erb
<h1>Условия использования</h1>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <hr>
  <h2>
    <%= user.id %> <%= user.email %>
  </h2>
  <p>
    <%= user.username %><br>
  </p>

  <hr>
<% end %>